version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - '$HOME/ktbd/volume/mysql:/var/lib/mysql'
  nginx:
    image: nginx:latest
    ports: 
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './src:/usr/share/nginx/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
